# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Box-height twins of a climb arm.

``__post_init__`` derives terrain, task space and start pool from ``target_box_height``, so a hydra
override lands too late; the height is pinned as a class field and named in the gym id instead.
"""

from isaaclab.utils import configclass

CLIMB_BOX_HEIGHTS: dict[str, float] = {"0p41": 0.41, "0p72": 0.72}
"""Token used in the class name and as the last modifier of the gym id, mapped to metres."""


def at_box_height(base: type, token: str) -> type:
    """One height twin of ``base``, pinning ``target_box_height`` and nothing else."""
    return configclass(
        type(
            f"{base.__name__}_{token}",
            (base,),
            {
                "__annotations__": {"target_box_height": float},
                "target_box_height": CLIMB_BOX_HEIGHTS[token],
                "__doc__": (
                    f"{base.__name__} on the {CLIMB_BOX_HEIGHTS[token]} m box.\n\n"
                    f"    Generated by ``at_box_height``; the arm itself is unchanged."
                ),
                "__module__": base.__module__,
            },
        )
    )


def build_height_twins(bases: dict[str, type], namespace: dict) -> None:
    """Bind both twins of every arm into ``namespace`` so ``module:Class`` entry points resolve."""
    for name, base in bases.items():
        for token in CLIMB_BOX_HEIGHTS:
            twin = at_box_height(base, token)
            twin.__module__ = namespace["__name__"]
            namespace[f"{name}_{token}"] = twin
