# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""One task family per real-world scan, generated from the generic arms in :mod:`scan_env_cfg`.

Arms differ between scans only in their :class:`~informed_exploration.terrains.config.scans.ScanSpec`.
The generated classes are bound into this module under their real names, so ``module:Class`` entry points resolve.
"""

from __future__ import annotations

from isaaclab.utils import configclass

from informed_exploration.terrains.config.scans import SCAN_SPECS, ScanSpec

from . import scan_env_cfg as _arms
from .scan_naming import ARM_NAMES, ARM_TASK_SUFFIX, env_cfg_name, runner_name, task_id  # noqa: F401

ARMS: dict[str, type] = {arm: getattr(_arms, f"ScanEnvCfg_{arm}") for arm in ARM_NAMES}
"""The generic arm class behind each arm name (see :mod:`scan_naming` for the names themselves)."""


def build_scan_family(spec: ScanSpec) -> dict[str, type]:
    """Every arm bound to one scan, keyed by class name; each subclass adds only the spec."""
    family: dict[str, type] = {}
    for arm, base in ARMS.items():
        name = env_cfg_name(spec, arm)
        doc = (
            f"{arm} arm on the {spec.snake} scan"
            f"{': ' + spec.notes if spec.notes else ''}.\n\n"
            f"    Generated by ``build_scan_family``; see :class:`~...scan_env_cfg.{base.__name__}`\n"
            f"    for what the arm does and ``terrains/config/scans.py`` for the terrain."
        )
        # Dunder keeps the spec off the config surface; `scan` re-bound since configclass reads own __dict__ only
        family[name] = configclass(
            type(
                name,
                (base,),
                {"__scan_spec__": spec, "scan": base.scan, "__doc__": doc, "__module__": __name__},
            )
        )
    return family


SCAN_FAMILIES: dict[str, dict[str, type]] = {
    snake: build_scan_family(spec) for snake, spec in SCAN_SPECS.items()
}
"""``{scan snake name: {class name: cfg class}}`` for every registered scan."""

# bind the generated classes into this module so `module:Class` entry points resolve
for _family in SCAN_FAMILIES.values():
    globals().update(_family)

__all__ = [
    "ARMS",
    "ARM_TASK_SUFFIX",
    "SCAN_FAMILIES",
    "build_scan_family",
    "env_cfg_name",
    "task_id",
    *sorted(name for family in SCAN_FAMILIES.values() for name in family),
]
